Crear docker-compose
ong-bitcoin-argentina/DIDI-SSI-Issuer-module pull request #117
Opened 2021-04-22 15:58 UTC by fedelmar

Crear docker-compose para levantar repositorio fácilmente en entorno local.

2021-04-22 16:07 UTC, MatiasOS requested changes

2021-04-22 16:07 UTC, MatiasOS commented on docker-compose/docker-compose.yml
> +    labels:
Estos labels de traefik no son necesarios

2021-04-22 16:07 UTC, MatiasOS commented on docker-compose/docker-compose.yml
> +      - "/didi/db-data:/data/db"
Estos 2 podríamos hacerlos local al repositorio? 
Con **./db-data:/data/db** y **./configs:/docker-entrypoint-initdb.d/mongo-init.js:ro** debería funcionar.

2021-04-23 18:33 UTC, tomaslosada submitted a review, later dismissed
Cambiar volúmenes para que sean locales al repo.

2021-04-23 18:33 UTC, tomaslosada commented on docker-compose/docker-compose.yml
> +      - "/didi/db-data:/data/db"
Coincido con Mati! El resto parece estar bien!

2021-04-26 12:32 UTC, MatiasOS approved these changes
:+1:

2021-04-26 12:33 UTC, Diegoro21 approved these changes

2021-04-26 12:50 UTC, merged