Documentar CertRoutes
ong-bitcoin-argentina/DIDI-SSI-Issuer-module pull request #119
Opened 2021-04-29 20:20 UTC by fedelmar

Documentación endpoints CertRoutes en Swagger

2021-04-29 22:52 UTC, Diegoro21 commented on routes/CertRoutes.js
> + *         - microCedentials
microCedentials es opcional.

2021-04-30 13:38 UTC, MatiasOS requested changes
Algunos cambios

2021-04-30 13:38 UTC, MatiasOS commented on routes/CertRoutes.js
> + *   /cert/find:
Acá falta los datos de la query

2021-04-30 13:38 UTC, MatiasOS commented on routes/CertRoutes.js
> + *   get:
POST

2021-04-30 13:38 UTC, MatiasOS commented on routes/CertRoutes.js
> + *     summary: Recuperar todas las credenciales marcadas como eliminadas
cambiar por: **Actualiza el estado de los certificados eliminados(deleted=true) a un estado de revocados (revocation= fecha de emisión)**

2021-04-30 16:43 UTC, MatiasOS approved these changes

2021-04-30 16:43 UTC, merged