Validar constantes cargadas
ong-bitcoin-argentina/DIDI-SSI-Issuer-module pull request #127
Opened 2021-05-05 14:57 UTC by Diegoro21

Validar que estén las constantes cargadas o mostrar error.

2021-05-05 15:29 UTC, MatiasOS requested changes

2021-05-05 15:29 UTC, MatiasOS commented on constants/Constants.js
> +if (process.env.MONGO_URL == null || process.env.MONGO_URL == '') throw new Error('No esta definida la varibale MONGO_URL');
MONGO_URL se genera  partir de otras variables. Ver linea 60

2021-05-05 15:29 UTC, MatiasOS commented on constants/Constants.js
> +if (process.env.DELEGATE_DURATION == null || process.env.DELEGATE_DURATION == '') throw new Error('No esta definida la varibale DELEGATE_DURATION');
DELEGATE_DURATION como tiene un valor por defecto no es necesario

2021-05-05 15:59 UTC, fedelmar submitted a review, later dismissed

2021-05-05 17:16 UTC, Diegoro21 commented on constants/Constants.js
> +if (process.env.ENABLE_INSECURE_ENDPOINTS == null || process.env.ENABLE_INSECURE_ENDPOINTS == '') throw new Error('No esta definida la varibale ENABLE_INSECURE_ENDPOINTS');
@fedelmar @MatiasOS en el .env no esta definida esta variable, la que esta es ISSUER_ENABLE_INSECURE_ENDPOINTS

2021-05-05 18:58 UTC, MatiasOS submitted a review, later dismissed

2021-05-06 12:01 UTC, MatiasOS approved these changes

2021-05-06 12:01 UTC, merged