[MM-513] Reemplazar librerias de uport
ong-bitcoin-argentina/DIDI-SSI-Issuer-module pull request #175
Opened 2021-10-07 16:26 UTC by fedelmar

Se reemplazan las librerías de uport utilizadas para el manejo de credenciales y emisores, reemplazándolas por métodos creados la librería BlockchainManager.

2021-10-12 18:44 UTC, MatiasOS requested changes
Unos pequeños cambios nomàs

2021-10-12 18:44 UTC, MatiasOS commented on services/MouroService.js
> +    const result = await BlockchainService.createVerifiableCredential(
Puede ser que ya no se este utilizando **vcPayload**?

2021-10-12 18:44 UTC, MatiasOS commented on __tests__/services/Mouro/createShareRequest.test.js
> +  test('Expect createShareRequest to throw on registerId cb', async () => {
**on missing registerID**

2021-10-13 23:13 UTC, Diegoro21 approved these changes

2021-10-15 15:49 UTC, MatiasOS approved these changes

2021-10-15 15:50 UTC, merged