[WIP][MM-586] Crear CRUD para las peticiones de credenciales
ong-bitcoin-argentina/DIDI-SSI-Issuer-module pull request #178
Opened 2021-11-30 14:46 UTC by fedelmar

- Se crea el modelo ShareRequest
- Se actualizan librerías BlockchainManager y mongoose a su ultima version
- Se crea función para la creación de tokens que autorizan a un emisor en el didi-server

2021-11-30 14:54 UTC, MatiasOS commented on models/dataTypes/ClaimsData.js
> +  iss: {
iss debería ser un array, porque son los issuers válidos.

2021-11-30 14:54 UTC, MatiasOS commented on models/dataTypes/ClaimsData.js
> +    required: true,
Y no le pongas required. Vamos a asumir que si no está, todos los issuers son válidos

2021-11-30 14:54 UTC, MatiasOS commented on constants/Constants.js
> +const CERT_CATEGORIES = [
Esta semana sacamos del horno DIDI SSI VC validator, así reemplazamos esto

2021-11-30 15:26 UTC, fedelmar commented on constants/Constants.js
> +const CERT_CATEGORIES = [
genial, cuando este la librería lo actualizo

2021-12-01 16:55 UTC, MatiasOS requested changes
Revisar, que algunos servicios hacen **console.log** y otros no. Estaría bueno hacerlo siempre o nunca.

2021-12-01 16:55 UTC, MatiasOS commented on controllers/shareRequest/deleteById.js
> +    return ResponseHandler.sendErr(res, err);
Fijate de mandarle la respuesta con error. Si no está implementado el método, copialo desde DIDI Server

2021-12-01 16:55 UTC, MatiasOS commented on routes/ShareRequestRoutes.js
> + *     summary: Manda un shareRequest a didi-server para ser guardarlo
**para guardarlo** o **para ser guardado** :D

2021-12-01 16:55 UTC, MatiasOS commented on routes/ShareRequestRoutes.js
> +  Validator.validateFile,
Qué file está validando acá?

2021-12-02 14:46 UTC, DoloresGarciaE approved these changes, later dismissed

2021-12-03 15:27 UTC, MatiasOS approved these changes, later dismissed

2021-12-10 19:35 UTC, MatiasOS requested changes

2021-12-10 19:35 UTC, MatiasOS commented on routes/RegisterRoutes.js
> + *   /register/shareRequests/{did}/{id}:
Esta ruta deberia ser **/register/{did}/shareRequests/{id}:**

De los register, dame el que tiene este did, y de los shareRequest de ese register dame el que tiene este id.

2021-12-10 19:35 UTC, MatiasOS commented on controllers/register/readShareRequestById.js
> +    return ResponseHandler.sendErr(res, err);
Acordate de usar el send error with status

2021-12-10 19:35 UTC, MatiasOS commented on controllers/register/readShareRequestsByDid.js
> +    return ResponseHandler.sendErr(res, err);
Acá tampoco te olvides de mandar el error con status

2021-12-10 19:52 UTC, MatiasOS approved these changes

2021-12-10 19:58 UTC, merged