Feature/me 21 create share resp endpoint
ong-bitcoin-argentina/DIDI-SSI-Issuer-module pull request #192
Opened 2022-05-20 23:21 UTC by DoloresGarciaE

- Se crea endpoint shareResponse
- Se crean los tests unitarios

2022-05-24 14:46 UTC, SantiagoMaresca commented on routes/ShareResponseRoutes.js
> + *       - shareRequests
este tag sería shareResponses, no?

2022-05-24 14:46 UTC, SantiagoMaresca commented on models/ShareResponse.js
> +    type: String,
capaz esta prop podria llamarse `jwt` para que sea más claro? , ya que es el jwt del shareResp?

2022-05-24 14:46 UTC, SantiagoMaresca commented on models/ShareResponse.js
> +    type: String,
capaz esta prop podria llamarse `jwt` para que sea más claro? , ya que es el jwt del shareResp?

2022-05-31 19:21 UTC, SantiagoMaresca commented on models/ShareResponse.js
>  // toDo:check if we have to save other properties
Podriamos eliminar este comentario y uno que hay en la linea 6 ?
En este caso eran solo aclaraciones.
Gracias!

2022-06-02 13:08 UTC, SantiagoMaresca commented on models/ShareResponse.js
> +    require: true,
```suggestion
    required: true,
```

2022-06-07 18:37 UTC, claudio-uslenghi commented on routes/ShareResponseRoutes.js
> + *     summary: Manda un shareResponse a didi-server para ser guardado
el summary seria recibe un shareResponse para ser guardado

2022-06-09 18:25 UTC, claudio-uslenghi requested changes

2022-06-09 18:25 UTC, claudio-uslenghi commented on routes/ShareResponseRoutes.js
> + *     summary: Manda un shareResponse a didi-server para ser guardado
Cambiar summary

2022-06-21 13:20 UTC, claudio-uslenghi approved these changes

2022-06-21 18:08 UTC, merged