Didi 625 multiblockchain
ong-bitcoin-argentina/DIDI-SSI-Issuer-module pull request #58
Opened 2020-11-12 13:31 UTC by uquevedoatix

Se puede registrar emisores de credenciales en blockchain

- Frontend: Registra emisor mediante un modal,  ver los registros en una tabla y ver detalladamente un registro. Se saco el renombrar emisor y se cambio el menú de Header, dejando solamente un "Salir" para cerrar sesión .

- Backend: Se creo un modelo de Registro y los endpoints de getAll(Obtener todos los registros), create(Se permite crear un registro), y getAllBlockchain(Devuelve todos los tipos de blockchain permitido). Al crear un registro se valida enviando un fetch a DIDI-server

2020-11-12 14:48 UTC, MatiasOS requested changes

2020-11-12 14:48 UTC, MatiasOS commented on issuer-back/routes/RegisterRoutes.js
> +			return ResponseHandler.sendRes(res, Constants.BLOCKCHAINS);
En lista de constantes veo Lacchain, BFA y RSK. Cómo se diferencian de las testnet? RSK Mainnet de RSK Testnet

2020-11-12 14:48 UTC, MatiasOS commented on issuer-front/src/app/setting/register-modal.js
> +			setNewRegister(register => ({ ...register, did: `did:ethr:${value}:${identity.did}` }));
Me parece que en el direccionamiento a mainnet el did es `did:ethr:0x....` En caso de que value sea el de mainnet, que es vacío, no quedaría como `did:ethr::0x....`? El error están en lo 2 veces seguidas 2 puntos `::`

2020-11-12 15:58 UTC, uquevedoatix commented on issuer-front/src/app/setting/setting.js
> +									id="user-select-input"
Es probable que estés haciendo referencia a un commit viejo, en el actual no existe tal documentación

2020-11-12 17:27 UTC, fsawadyatix commented on issuer-back/models/Register.js
> +	key: {
para qué serviría key?

2020-11-12 17:29 UTC, fsawadyatix commented on issuer-back/routes/RegisterRoutes.js
> +			return ResponseHandler.sendRes(res, {});
debería devolver el resultado de newRegister

2020-11-12 17:33 UTC, fsawadyatix commented on issuer-back/services/BlockchainService.js
> +		const data = await sendDidToIssuer(did, name);
no es al issuer sino a didi

2020-11-12 17:33 UTC, fsawadyatix commented on issuer-back/services/BlockchainService.js
> +		if (!registers) return Promise.reject(Messages.REGISTER.ERR.GET);
no debería dar error nunca, salvo un caso excepcional, si no hay debería ser lista vacía

2020-11-12 17:34 UTC, fsawadyatix commented on issuer-back/services/BlockchainService.js
> +		const response = await fetch(Constants.DIDI_API + "/issuer", {
mejor no usemos fetch, salvo que en otro lado se esté usando, estoy seguro que el issuer ya le está pegando a endpoints de DIDI, hay que usar eso

2020-11-12 17:35 UTC, fsawadyatix commented on issuer-front/src/app/setting/register-modal.js
> +			setNewRegister(register => ({ ...register, did: `did:ethr:${value}:${identity.did}` }));
cierto, quedó raro ahí

2020-11-12 17:40 UTC, fsawadyatix commented on issuer-back/routes/RegisterRoutes.js
> +			return ResponseHandler.sendRes(res, Constants.BLOCKCHAINS);
Teóricamente las configs en varios lugares soportan una configuración de 3 blockchains. Entonces para RSK uno tendría testnet o mainet de forma excluyente. O al menos eso habíamos charlado.

2020-11-16 18:33 UTC, fsawadyatix requested changes

2020-11-16 18:33 UTC, fsawadyatix commented on issuer-back/routes/RegisterRoutes.js
> +	Validator.validate([
faltan campos no?

Estaría bueno chequear que el did venga de una de las blockchain soportadas

2020-11-16 18:33 UTC, fsawadyatix commented on issuer-back/routes/RegisterRoutes.js
> +			const { did, name, key } = req.body;
chequeate antes que no exista el did, así tiramos un 400 bad request

2020-11-16 18:33 UTC, fsawadyatix commented on issuer-front/src/app/setting/register-modal.js
> +			setNewRegister(register => ({ ...register, did: `did:ethr:${value}:${identity.did}` }));
Uri, chequeate bien que no quedé mal formado el string

2020-11-17 13:09 UTC, fsawadyatix approved these changes

2020-11-17 14:07 UTC, closed without merging