Didi 785 fix create delegates
ong-bitcoin-argentina/DIDI-SSI-Issuer-module pull request #90
Opened 2021-01-11 15:22 UTC by uquevedoatix

Didi-785    Error al intentar crear delegaciones

También incluye las siguientes card:

Didi-863    Salto de renglon al mostrar en la columna los roles
Didi-866    Problemas con el resize de las tablas cuando se usa un DatePicker

2021-01-11 19:50 UTC, nlaitanatix requested changes

2021-01-11 19:50 UTC, nlaitanatix commented on issuer-back/models/Register.js
> +	if (register) {
Falta el contemplar el caso en que no exista el register

2021-01-11 19:50 UTC, nlaitanatix commented on issuer-back/routes/utils/DidClean.js
> +const getDidClean = did => {
```suggestion
const getCleanedDid = did => {
```

2021-01-11 19:50 UTC, nlaitanatix commented on issuer-back/routes/utils/DidClean.js
> +	getDidClean
```suggestion
	getCleanedDid
```

2021-01-11 19:50 UTC, nlaitanatix commented on issuer-front/src/app/main/Main.js
> +		const registerId = data.registerId;
```suggestion
		const { did, name, registerId } = data;
```

2021-01-11 19:50 UTC, nlaitanatix commented on issuer-front/src/app/profile/profile-table-helper.js
> +						style={{ marginRight: "5px", fontSize: "12px", fontWeight: "500", margin: "4px 2px" }}
Si hay mas de un estilo en linea, mejor dar estilo mediante clases css (o crear un `<CustomChip />`)

2021-01-11 23:31 UTC, MatiasOS commented on issuer-front/src/app/main/Main.js
> +		const registerId = data.registerId;
:heart:

2021-01-12 22:07 UTC, nlaitanatix approved these changes

2021-01-13 15:09 UTC, merged